### PR TITLE
Fixes issue with tracking an inherited model

### LINKED ISSUE #269: Tracking an inherited model (abstract class)
As seen in https://github.com/treyhunner/django-simple-history/pull/112 and [docs](http://django-simple-history.readthedocs.io/en/latest/advanced.html#allow-tracking-to-be-inherited) the ``HistoricalRecords`` can now be used with ``inherited = True`` to tracking inherited models "automatically".

Despite this, I came across an issue with ``Django 1.10.6`` and the updated version of this repository ``master`` branch (https://github.com/treyhunner/django-simple-history/commit/d76e446c3c45dbc81a9ac6db9297c5649e27c1b4).

The issue can be reproduced with this example:

```
django-admin startproject myproject
cd myproject
django-admin startapp myapp
touch myproject/models.py
```

*myproject/models.py*
```python
# -*- coding: utf-8 -*-
from django.db import models
from simple_history.models import HistoricalRecords


class GenericModel( models.Model ):
    class Meta:
        abstract = True

    history = HistoricalRecords( inherit = True )
```

*myapp/models.py*
```python
# -*- coding: utf-8 -*-
from myproject.models import GenericModel


class MyModel( GenericModel ):
    class Meta:
        app_label = 'myapp'
```

*myproject/settings.py*
```python
...
INSTALLED_APPS = [
    ...
    'simple_history',
    'myapp',
]
...
MIDDLEWARE = [
    ...
    'simple_history.middleware.HistoryRequestMiddleware',
]
```

After that, run ``python manage.py makemigrations`` and the following error will be raised:
```
RuntimeError: Model class myproject.models.HistoricalMyModel doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

Any ideas about what is going on?

### PR DESCRIPTION
**Pull request by rossmechanic**
Fixes #269 . @macro1 I wrote this so that it handles the different use cases (when `HistoricalRecords` is set as a field vs. when `register` is used), but am open to another solution if you have a cleaner one that comes to mind. For an abstract base model defined in app1 and a concrete implementation defined in app2, this makes sure that the historical model is also in app2 as opposed to app1.

### CODE REVIEW

**Comment by rossmechanic** [comment]
@macro1 would you mind taking a look at this?

**Comment by macro1** [comment]
Sure. I need to take some time to sit down and actually work through the code though. This touches some of the weirder parts of django-simple-history.

**Comment by rossmechanic** [comment]
@macro1 Thanks. Happy to answer any questions for you. Took awhile with my debugger to figure out what exactly was going on here...

**Comment by rossmechanic** [comment]
@macro1 any update on this?

**Comment by rossmechanic** [comment]
@treyhunner @macro1 ?

**Comment by rossmechanic** [comment]
@rwlogel has a solution (#352) that makes more sense. Closing this, adding the tests from here to that branch, and then merging that.

**Pull request closed without merging**
