### PR TITLE
Correct module for history model of inherited model

### PR DESCRIPTION
**Pull request by rwlogel**
If base model is in a different module the history model for the
inherited model should be in the same module as the inherited model

### CODE REVIEW

**Comment by rwlogel** [comment]
The coverage tests are failing because the error conditions of the unit tests are not being executed which is the expected result.  Should these tests be in a different file or implemented differently?

**Comment by rwlogel** [comment]
One of the key features missing from #324 is the change to how `importlib.import_module` (models.py lines 96-101 of this diff) is called.  I think that the code should actually be using `history_model.__module__` all the time but I was concerned with breaking more things then I had time to test for.

**Comment by rwlogel** [comment]
For example if you add the unit tests added to this request to the #324 request they both fail because the `ConcreteExternal` and `ConcreteExternal2` class are not registered in the `tests.models`  module.

**Comment by rossmechanic** [comment]
Wanted to add some tests and change a few issues with wording so opened a new PR with that that I'm about to merge (#355). Thanks for the solution @rwlogel

**Pull request closed without merging**
