### PR TITLE
Add new constructor options to HistoricalRecords class

### PR DESCRIPTION
**Pull request by rwlogel**
- Provide history_id_field to change the field type for history_id
- Provide user_model to use an alternative model for tracking history_user

### CODE REVIEW

**Comment by rossmechanic** [comment]
This would solve for #116. Happy to discuss allowing UUIDs for the historical tables, but I'm less inclined to allow for a separate user model. Want to split this up into two PRs and we can discuss them separately? @rwlogel

**Comment by rossmechanic** [comment]
No worries. Let's definitely split the changes into two PRs so that we can have the discussions separately. Happy to allow UUIDs on history IDs as I've seen that functionality requested multiple times. 

More hesitant about allowing a CustomUser model as it's rare to see Django programmers using a user model that doesn't extend `AUTH_USER_MODEL`, and I'm worried about any possible side effects (the way we track users with middleware is a little magic-y). 

However, I understand your use case – essentially keeping sensitive fields in a separate table, right? Going to close this PR and ask you to open these two features in separate PRs and we can discuss them separately.

**Comment by rwlogel** [comment]
Changing the user model doesn't work with the built in middleware, as documented in the PR it requires the user of the `_history_user`.  I will submit new PR's shortly and try to include an example of what a middleware with the a custom user model may look like.

**Comment by rossmechanic** [comment]
Thanks @rwlogel

**Pull request closed without merging**
