### PR TITLE
fix #575 use django model_to_dict to detect changes in parent models

### LINKED ISSUE #575: diff_against doesn't detect changes to parent model attributes when using inherited models
**Describe the bug**
`HistoricalChanges.diff_against` won't detect changes in inherited models (`inherit=True`).

Problem resides at the way `_model_to_dict` serializes fields.

~~~ python
def _model_to_dict(model):
    return json.loads(serialize("json", [model]))[0]["fields"]
~~~
It uses `django.core.serializers.serialize`, but as explained [here](https://docs.djangoproject.com/en/2.2/topics/serialization/#inherited-models):

> if you have a model that uses multi-table inheritance, you also need to serialize all of the base classes for the model. This is because only the fields that are locally defined on the model will be serialized.

So it ignores any fields in the parent class.

**To Reproduce**
1. Have inherited models:

~~~ python
class Place(models.Model):
    name = models.CharField(max_length=50)

class Restaurant(Place):
    serves_hot_dogs = models.BooleanField(default=False)
~~~

Then from a `Restaurant` instance change an attribute from the parent class `Place.name`

~~~ python
r = Restaurant.objects.create(name="McDonalds")
r.name = "BurgerKing"
r.save()
~~~

Now try to detect changes:

~~~ python
new_record, old_record = r.history.all()
delta = new_record.diff_against(old_record)
for change in delta.changes:
    print("{} changed from {} to {}".format(change.field, change.old, change.new))
~~~

But it won't detect the `name` field so it doesn't detect any changes and `delta.changes=[]`

**Environment (please complete the following information):**
 - OS: Ubuntu 18.10
 - Django Simple History Version: 2.7.2
 - Django Version: 2.2.2

### PR DESCRIPTION
**Pull request by marcanuy**
Use Django's `model_to_dict` as suggested at https://github.com/treyhunner/django-simple-history/issues/575#issuecomment-514047309 to detect changes in a parent model when using `inherit=True`.

## Related Issue

https://github.com/treyhunner/django-simple-history/issues/575
Related with https://github.com/treyhunner/django-simple-history/pull/479

## How Has This Been Tested?

Added test

## Types of changes

- [ X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] I have run the `make format` command to format my code
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] I have added my name and/or github handle to `AUTHORS.rst`
- [ ] I have added my change to `CHANGES.rst`
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by kseever** [comment]
Hi Marcelo! Thanks for the contribution! The fix looks good to me. The only ask I have is that you add a line in CHANGES.rst about it, noting that the change is backwards-incompatible so that we include it in the next minor rev.

**Comment by rossmechanic** [comment]
Hi @marcanuy any update on this?

**Comment by marcanuy** [comment]
Hi @rossmechanic @kseever , I've added a line to `changes.rst` explaining this PR. Didn't mention it was backwards-incompatible as I think it doesn't break any previous functionality, does it? If so please tell me and I will include it.

**Comment by kseever** [comment]
The backwards-incompatibility lies in that current callers might be subtly expecting no deltas to result from changes made in parent models. If we include this as a bugfix revision, some applications or tests might break for reasons that could be hard to understand. I think it would be good to call attention to in the changelog for folks who are looking to upgrade in case they have parent/child models that they are using the diff functionality on.

**Comment by marcanuy** [comment]
@kseever Thanks for the clarification, just updated changes file

**Comment by ses4j** [comment]
This change silently broke our usage of simple_history, unfortunately.  We use `editable=False` on a number of fields that we want to track with simplehistory.  Django's built-in method excludes these fields because they are not needed for forms, but we still want them in history!  Right now we're pinning to before this change.  Any ideas for a compromise?

**Pull request merged**
