### PR TITLE
added py36 and Django 1.11 to test environments

### PR DESCRIPTION
**Pull request by rooterkyberian**
* fixed up tests so they work with Django 1.11
* added python 3.6 as test enviroment
* removed python <3.5 versions from tox for django-trunk as next Django version (2.0) won't support anything less https://docs.djangoproject.com/en/1.11/faq/install/#what-python-version-can-i-use-with-django

### CODE REVIEW

**Comment by macro1** [comment]
Did you want to add yourself to [AUTHORS.rst](https://github.com/treyhunner/django-simple-history/blob/master/AUTHORS.rst) as well?

**Comment by rooterkyberian** [comment]
sure, done

**Comment by clintonb** [comment]
@macro1 any plans to merge/release this?

**Comment by leportella** [comment]
This seems good! It would be better to add the support on documentation, but I think we can leave it to another PR. Thank you!

**Comment by clintonb** [comment]
@leportella any chance you can create a new release on PyPI?

**Pull request merged**
