### PR TITLE
Respect the to_field setting and the target field type

### PR DESCRIPTION
**Pull request by arski**
https://github.com/treyhunner/django-simple-history/issues/182

Hope this is enough tests? :)

### CODE REVIEW

**Comment by arski** [comment]
I guess not :D

**Comment by arski** [comment]
Is the code coverage test performed on a certain version of django? if that's the case then I can't really fix it.. the pre-1.6 code version would work in later versions of django too (getting the to_field from rel.field_name), but it's not really the right approach, I think at least?

Let me know your thoughts :) thanks

**Comment by macro1** [comment]
Coverage should be cumulative. I'm not sure why the commit requirement is 95%, that's pretty high. I wonder if the assumption was that it's requiring 95% coverage of the new lines being added. Anyway, those are new so I wouldn't worry too much. I'll try to look at this later this week.

**Comment by arski** [comment]
Yeah I'm pretty sure it's counting the new lines - since the coverage test runs on django 1.4, 1 line out of 6 new ones that is not applicable to django 1.4 is not covered by the coverage test.. (5/6 = 83.33) :)

and thanks!

**Pull request merged**
