### PR TITLE
Add support for admin inlines

### PR DESCRIPTION
**Pull request by mathieuhentges**
The inlines couldn't be displayed in the admin form view. 

I added the 'inline_admin_formsets' entry in context to make them available.

### CODE REVIEW

**Comment by rossmechanic** [comment]
@mathieuhentges Do you mind attaching screenshots to show what this looks like after the changes? Thanks. Also please fix merge conflicts.

**Comment by rossmechanic** [comment]
@mathieuhentges Any updates? Or would you like me to take this over?

**Comment by rossmechanic** [comment]
Closing this since I haven't heard from @mathieuhentges

**Comment by merwok** [comment]
@rossmechanic were you able to take this over?

I think this could be quite useful!

**Comment by rossmechanic** [comment]
Haven't been able to get around to it yet. I wanted to make it easy to run a sample app within the repo (so it would be easy to test admin features). Once I get that done, it'll be really easy to knock out a bunch of the bugs/features we want on the admin side. Feel free to work on this if you'd like though. I'd be happy to accept a PR

**Comment by merwok** [comment]
I’ll poke my co-worker Mathieu or see if I find the time myself!

I opened a ticket so that this doesn’t get forgotten.

**Comment by nickvellios** [comment]
This PR _does_ work to allow inlines to be displayed in the history detail, however it is always the current state of the related models, not the state they were in when saving.  In many cases, this is not a true representation of the state of this snapshot as you would have saved it in the admin.

Is there currently a branch working to address this?

**Comment by rossmechanic** [comment]
Nothing working to currently address this @nickvellios, but I'd be happy to discuss a possible solution

**Comment by nickvellios** [comment]
This is something I quickly hacked together based off of this PR just to see how close I could get to a solution.  It is far from ideal because there is no way to be sure the 5 second fuzzy history_date filter will be accurate.  For example, if something hangs between saving the models, or if multiple saves take place within a 5 second period (multiple users or API).

I'm struggling to find a way to accurately represent the state of related objects with how the historical models are currently structured.

`
        historical_obj = get_object_or_404(model, **{
            original_opts.pk.attname: object_id,
            'history_id': version_id,
        })
        historical_date = historical_obj.history_date
        adjusted_historical_date = historical_date + datetime.timedelta(seconds=5)
        for FormSet, inline in self.get_admin_formsets_with_inline(
                *[request]):
            prefix = FormSet.get_default_prefix()
            prefixes[prefix] = prefixes.get(prefix, 0) + 1
            if prefixes[prefix] != 1 or not prefix:
                prefix = "%s-%s" % (prefix, prefixes[prefix])
            inline_qs = inline.get_queryset(request)
            inline_ids = inline_qs.values_list('id', flat=True)
            history_inline_model = inline_qs.first().history.model
            historical_ids = history_inline_model.objects\
                                    .filter(id__in=inline_ids, history_date__lte=adjusted_historical_date)\
                                    .order_by('-history_date')[:inline_qs.count()]\
                                    .values_list('history_id', flat=True)
            historical_queryset = history_inline_model.objects.filter(history_id__in=historical_ids)
            formset_params = {
                'instance': obj,
                'prefix': prefix,
                'queryset': historical_queryset,
            }
            if request.method == 'POST':
                formset_params.update({
                    'data': request.POST.copy(),
                    'files': request.FILES,
                    'save_as_new': '_saveasnew' in request.POST
                })
            formset.append(FormSet(**formset_params))
`

**Pull request closed without merging**
