### PR TITLE
Add Django 1.8 support

### LINKED ISSUE #156: Django 1.8: ImportError: No module named related
```
  File "/Users/thekgf/CentriFile/allay/venv/lib/python2.7/site-packages/simple_history/models.py", line 13, in <module>
    from django.db.models.related import RelatedObject
ImportError: No module named related
```

Django 1.8 has made some changes here and removed the RelatedObject API. More details are here: https://docs.djangoproject.com/en/dev/releases/1.8/#model-attribute-on-private-model-relations

### PR DESCRIPTION
**Pull request by macro1**
There have been a couple pull requests, so I decided to make a pull request of what I have so far. As noted in #156 the internal API for related fields has changed and the `rel` and `related` field attributes have merged.

Initially I looked at maintaining what we currently have with CustomForeignKey, but I don't think it would be wise to continue supporting it in the future if there is any chance of removing it. The code bellow appears to work for 1.8, I haven't worked through making it backward compatible.

@rodxavier or @RossLote: If this helps you sort out one of your branches, please update or reopen your PR so we can add support once we find a fix.

Closes #157
Resolves #156

### CODE REVIEW

**Comment by macro1** [comment]
Oh. I just realized what could be causing the error. The model doesn't exist still the tests are started, so it wasn't part of the test db setup. I'm not sure why I can't reproduce it locally, but that makes sense I think.

**Comment by KevinGrahamFoster** [comment]
Awesome, thanks Micah!

**Comment by macro1** [comment]
This bring 1.8 comparability to master, there will be a release soon.

**Comment by RafaelOrtiz** [comment]
Hi any ETA for this release ?

btw Thanks for your work!.

**Pull request merged**
